### ISSUE TITLE
[Feature Request] Allow setting the default sorting via config file

### ISSUE THREAD

**Issue by eugnma** [VladimirMarkelov/ttdl#25]
Finally I found a project I can switch form `Todo.txt CLI`, but I cannot set the default sorting which is implemented in `Todo.txt CLI`, is it possible to add the feature in TTDL?

**Comment by VladimirMarkelov** [comment]
Did you mean sort by priority? I see that it does not work in TTDL as expected. I'll look into it

**Comment by eugnma** [comment]
> Did you mean sort by priority? I see that it does not work in TTDL as expected. I'll look into it

Currently I can sort with command options (e.g. `ttdl ls -s=,due`), but I would like set it as the default sorting via config file, means If I use `ttdl ls` without sorting, it uses the default sorting from config file.

**Comment by VladimirMarkelov** [comment]
Done! And crate is updated. I hope it is what you need :)

New `sort` option in general section - please check the end of updated `ttdl.toml` in repository.

**Comment by eugnma** [comment]
Cool, this is what I wanted 👍, thanks!
