### ISSUE TITLE
feature request: --set-due argument should decode human-readable dates

### ISSUE THREAD

**Issue by obbardc** [VladimirMarkelov/ttdl#28]
Currently the `--set-due` argument requires a date, it'd be nicer if it could accept a human-readable form like:

--set-due=tomorrow
--set-due=3d
--set-due=1w
--set-due=1m

```
$ ttdl new snakes
Added todo:
# D P Created    Finished   Due        Threshold  Spent  Subject
-----------------------------------------------------------------
4                                                        snakes
$ ttdl edit 4 --set-due=2020-07-03
Changed todos:
# D P Created    Finished   Due        Threshold  Spent  Subject
-----------------------------------------------------------------
4                           2020-07-03                   snakes
-----------------------------------------------------------------
1 todos (of 4 total)
```

**Comment by VladimirMarkelov** [comment]
I am close to publishing a new version with this feature. But I have a question: I am going to add more "special" dates(besides `tomorrow|tmr|tm` and `today`) and I am not sure how to make them easy to understand. I added weekdays: `--set-due=fri` and `--set-due=next-fri`. What real due date do you expect from both commands for a date `2020-07-10` that is Friday? At this moment it is ambiguous(I can interpret `fri` and `next-fri` in two ways).

**Comment by thomasjfox** [comment]
While testing out the new feature today I didn't give it much thought and tried "due:tuesday". That is not recognized at the moment.

We might think about adding full day names for "due:" in addition to the abbreviation.

**Comment by VladimirMarkelov** [comment]
I agree. It makes sense.

**Comment by thomasjfox** [comment]
I took a look around the net what other implementations do. While there are quite a few parsers, many of them don't handle cases like "Monday after two weeks", just plain "Monday".

Two examples:

1. TaskWarrior: Too many hardly used knobs IMHO:
https://taskwarrior.org/docs/dates.html
https://taskwarrior.org/docs/named_dates.html

2. Official PHP implementation:
https://www.php.net/manual/en/datetime.formats.relative.php
https://www.php.net/manual/en/function.strtotime.php

```
echo strtotime("next Thursday"), "\n"
-> Thursday this week (if NOW is f.e. Tuesday)
````

I'll also ask coworkers tomorrow regarding https://github.com/VladimirMarkelov/ttdl/issues/28#issuecomment-657252837

**Comment by VladimirMarkelov** [comment]
Thank you for research! It seems that having "next DAY_OF_WEEK" adds ambiguity. So, we can keep simple WEEKDAY without any prefix and always choose this DAYOFWEEK in the future(in other words, it is always neither in the past not today).

**Comment by obbardc** [comment]
I agree keeping it simple is best.
Friday should mean the next Friday in the calender, if I wanted it to be
set to any other Friday I should have to put in a date.

**Comment by VladimirMarkelov** [comment]
OK. It seems done. If it looks good, I will publish new version. The current rules:

Numbers (shortcuts):

- `single number` = day of month
- `number-number` = month-day of month

Named:

- `today`, `tomorrow`, and `day of week`

Extra rules:

- `day of week` can be full word, or abbreviated to 2 or 3 first letters
- except `today` all other dates are always in the future
- setting day of month in `single number` or `month-day` to 31 always sets the due date to the last day of month. So, one does not have to remember how many days the current month has. It is a bit simplified description but you get the idea

**Comment by thomasjfox** [comment]
I think the new rules are perfect. Great job!

Personally I'll probably use "tuesday" or "14d" the most: A task is either on a fixed day soon or something more vague like "in two weeks". Example: "check bicycle tire pressure due:30d"

**Comment by VladimirMarkelov** [comment]
Thank you all for the discussion. Closing the issue as done one.
