### ISSUE TITLE
Want to list tasks which have no due date or have a due date within 2 weeks

### ISSUE THREAD

**Issue by manfredlotz** [VladimirMarkelov/ttdl#39]
This is TTDL Version 0.10.2, Fedora 32. 

Is it possible to list tasks which have no due date at all or have a due date within, say 2 weeks?

**Comment by VladimirMarkelov** [comment]
It depends:

- if you do not have overdue tasks(or it is OK to show overdue ones for `within 2 weeks`), command `ttdl list -due=none..2w` show do the job: it shows tasks with empty due date or due date is less than or equal to `today+2 weeks`
- if you want to exclude overdue todos, at this moment there is no way to do it, but it can be added. In this case we just have to decide how to pass it to the application. I see at least two ways: 1) extra syntax for `none`, like `--due=today..2w,none`, and 2) `--due=today..2w --due=none`. As of latter case, I am not sure if it is easy to parse with used library - I need to check. Maybe there are more elegant solution.

**Comment by manfredlotz** [comment]
Thanks for the quick reply.

It it ok if overdue task(s) are shown. I just didn't think of `--due=none..2w` which solves it nicely. Great!
