### ISSUE TITLE
Add filter for no context or no tags

### ISSUE THREAD

**Issue by swalladge** [VladimirMarkelov/ttdl#41]
This is something that I'm looking for to support my gtd-like workflow, where no context == inbox.

Given the todo.txt contents:

```
2020-12-25 task 1 @next
2020-12-25 task 2 @backlog
2020-12-25 task 3
```

A command like `ttdl list --no-context` should output:

```
 # D P Due        Subject
--------------------------
 3                task 3
```

Ditto for tags.

**Comment by VladimirMarkelov** [comment]
Good idea.

Though, maybe we can go with `--context none` - to be consistent with other fields which support `none`. I doubt `none` as a value for a tag or a context makes sense :)

**Comment by VladimirMarkelov** [comment]
In a new branch(for both todo_lib and ttdl) I added filtering todos with `--context`, `--project`, and `--tag`. All accept comma-separated list of values including special ones(`none` and `any` - as other filters accept). In addition, all support basic pattern matching (`*txt`, `txt*`, `*txt*` - end with, start with, contain the text `txt`). After improving README, I'll publish the new versions.

**Comment by VladimirMarkelov** [comment]
Master branch updated

**Comment by swalladge** [comment]
@VladimirMarkelov thanks, this is great! :D
