### ISSUE TITLE
different version for git tag and ttdl version

### ISSUE THREAD

**Issue by reini-1** [VladimirMarkelov/ttdl#48]
The current version 2.x has the github tag 2.0.1 but the downloaded file has version 2.0.0 and there is no download executable for 2.0.0.

https://github.com/VladimirMarkelov/ttdl/releases/download/2.0.1/ttdl_2.0.0_win_x64.zip

Maybe you can synchronize tags and version number?

Thanks in advance.

**Comment by VladimirMarkelov** [comment]
The only difference between 2.0.0 and 2.0.1 is `changelog` (that I forget to update in 2.0.0). So the binary is the same for both versions. I'll replace 2.0.1 release with new 2.0.2 tag that will include updated README and the recompiled binaries(with updated libraries).

**Comment by VladimirMarkelov** [comment]
Modified existing 2.0.1 - now it is 2.0.3 (there were more than one discrepancy, so I increased version to make everything the same)
