### ISSUE TITLE
Hide hidden tasks (h:1)

### ISSUE THREAD

**Issue by SevereOverfl0w** [VladimirMarkelov/ttdl#49]
Extension is documented in SimpleTask: https://github.com/mpcjanssen/simpletask-android/blob/46f40acec52e4270349bca273fe0459a88fb0eaf/app/src/main/assets/extensions.en.md.  I use this to keep a list of projects/contexts without tasks, but that may have them later.  This make it easier to use completion with todo.txt.

Right now, these tasks show up by default.

**Comment by VladimirMarkelov** [comment]
> These tasks will not be shown by default. You can temporarily display them from the Settings

It seems there must be a way to show them. First, I thought about extending the existing flag `--all`, so it displays hidden as well. But after a little thinking, I am not sure. Maybe separate option like `--hidden` is better.

**Comment by VladimirMarkelov** [comment]
Commit https://github.com/VladimirMarkelov/ttdl/commit/23f0681bddd56c10b8e79ddf789a7ab15b2daa6d is the last one for the feature: it includes documentation changes.

In brief:

- The current rule: if a task has the tag `h` and its value does not equal `0`, the task is hidden. Setting `h:0` turn a task into a regular one
- new option `--hidden`(off by default) makes a command include hidden for processing. The only command which always enables `--hidden` automatically are command to support shell auto-completion.

**Comment by SevereOverfl0w** [comment]
Nice, that will work well for me!
