### ISSUE TITLE
Filter to exclude context

### ISSUE THREAD

**Issue by SevereOverfl0w** [VladimirMarkelov/ttdl#51]
I have a context for "Things to read" which is a pretty big list!  I'd love to be able to hide it. I thought something like `ttdl ls -@ThingsToRead` or `ttdl ls !@ThingsToRead` would work.

**Comment by VladimirMarkelov** [comment]
Thanks for the suggestion of the new feature. I think, it makes sense to support multiple exclude items as other applications(e.g, archivers and their file exclude masks) does.

**Comment by VladimirMarkelov** [comment]
I moved it to `3.0` as it requires modifying `todo_lib` interface - to include extra fields to a request. I think, it means "breaking compatibility with 2.x". That was why I announced `2.1` and marked this one `3.0`. It does not mean that I put it to my backlog for long.
