### ISSUE TITLE
--due not working as before

### ISSUE THREAD

**Issue by manfredlotz** [VladimirMarkelov/ttdl#54]
I updated to ttdl 3.0.0

Before when doing 

```
ttdl list  pattern --due=none..45d
```
I got listed all tasks without due date as well.

With 3.3.0 this is no longer true. Now, tasks without any due date won't get listed. Anything has changed here?

**Comment by VladimirMarkelov** [comment]
Due date was the only date which did not use common filtering code. I fixed it and it should work now. Release 3.0.1 with the fix on `crates.io` is published.

**Comment by VladimirMarkelov** [comment]
I have not generated new binaries. I am going to do it when I release `3.1.0`
