### ISSUE TITLE
Problem with ttdl done

### ISSUE THREAD

**Issue by manfredlotz** [VladimirMarkelov/ttdl#55]
There is a problem with `ttdl done` which did exist prior to 3.0.0. I just forgot to report it.

Doing 

```
ttdl done  14,20-22
```
gives

```
No todo was completed
```

but 

```
ttdl done 14
ttdl done 20-22
```
works fine.

**Comment by VladimirMarkelov** [comment]
I have not touched the code that parses ID list. I'll check it.
