### ISSUE TITLE
Panics when output is piped to head & family

### ISSUE THREAD

**Issue by SevereOverfl0w** [VladimirMarkelov/ttdl#59]
```
❯ ttdl list | head -1
 # D P Created    Finished   Due        Subject
Failed to print to stdout: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
Failed to print to stdout: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
...
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1017:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by VladimirMarkelov** [comment]
Thanks for the report. I cannot reproduce it on Windows, it does not panics. Interesting. 

```
PS C:\docs> ttdl | coreutils.exe head -1
 # D P Created    Due        Subject
PS C:\docs> ttdl | coreutils.exe head -2
 # D P Created    Due        Subject
-------------------------------------
```

I need to run a Linux machine somewhere to test.

**Comment by VladimirMarkelov** [comment]
I redesigned the output mechanism. On Ubuntu 22, the new binary works without panicking.

**Comment by SevereOverfl0w** [comment]
There's no panic, but there is still `Failed to print to stdout: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }` which I wouldn't expect either.  For example, `cat foo.txt | head -1` wouldn't error that the remaining lines to stdout were closed.

**Comment by VladimirMarkelov** [comment]
Ouch. I found a call that I have missed. I'll fix the call and publish a new release.

**Comment by VladimirMarkelov** [comment]
`3.4.2` includes another fix for "broken pipe"

**Comment by SevereOverfl0w** [comment]
Works on my machine! Thanks!
