### ISSUE TITLE
Creation date not updated on recurring task completion

### ISSUE THREAD

**Issue by SevereOverfl0w** [VladimirMarkelov/ttdl#61]
Given a todo.txt of:

```
2022-01-01 do the thing rec:5d t:2022-08-28
```

and the command: `ttdl done 1` I would expect the resulting todo.txt to look like:

```
x 2022-08-28 2022-01-01 do the thing rec:5d t:2022-08-28
2022-08-28 do the thing rec:5d t:2022-09-02
```

But instead the new command retains the original creation date:

```
x 2022-08-28 2022-01-01 do the thing rec:5d t:2022-08-28
2022-01-01 do the thing rec:5d t:2022-09-02
```

**Comment by VladimirMarkelov** [comment]
Yes, it makes sense. I'll fix it.

**Comment by VladimirMarkelov** [comment]
Sorry, I closed the issue before I had fixed it. Version `3.4.4` (`3.4.3` is the same) should work as expected

**Comment by SevereOverfl0w** [comment]
Looking good!
