### ISSUE TITLE
Poor contrast on light theme

### ISSUE THREAD

**Issue by alexdavid** [VladimirMarkelov/ttdl#71]
Hi, thanks for writing ttdl!

I use a light theme during the day and ttdl defaults to white text which is difficult to read. Looking through the color configuration there doesn't seem to be a way to set the default color used.

In my opinion `default_color` should just use the default terminal fg color which I believe we can accomplish with `set_fg(None)` rather than `set_fg(Some(Color::White))`. However if you don't like that approach maybe we can just make `default_color` configurable instead?

I'm happy to add a PR if you let me know your preferred strategy.

**Comment by VladimirMarkelov** [comment]
Hi,
thank you for the idea.

if `set_fg(None)` works as expected everywhere(I have not tried), it is a good thing to implement. Though, having a `default_color` in config also makes sense. We can do this way: by default the configuration does not have `default_color` set(the line is in section `colors` but the line is commented out). The config reader defaults it to `None`. In this case we have both: good default for everyone and it is configurable.

**Comment by VladimirMarkelov** [comment]
I added a default color to configuration. By default, the default foreground color is `None`, not `White`. 

- If you can, please try my current working branch https://github.com/VladimirMarkelov/ttdl/tree/def-clr-none . If it works for you fine, I'll merge this into master and issue a new release. If it doesn't, please try to fix at your side and open an MR for this branch
- if you cannot, I'll merge the branch as is(it works well for me and my terminal with default theme) and issue a new release

**Comment by alexdavid** [comment]
Ah sorry I missed your messages. Yes this works great as it uses the default theme's fg color. Thanks for the implementation and quick turn around!

**Comment by VladimirMarkelov** [comment]
> Ah sorry I missed your messages. Yes this works great as it uses the default theme's fg color. Thanks for the implementation and quick turn around!

You're welcome!
