### ISSUE TITLE
Syntax highlighting mixes up tags and projects

### ISSUE THREAD

**Issue by chillenzer** [VladimirMarkelov/ttdl#74]
Hi, thanks for the nice tool. I've been using it for a while and really like the simplicity. Just updated to the latest version and had a look at the syntax highlighting feature. It looks nice but I ran into the following issue: When I've got a colon in my project's name, it is highlighted as a tag and not a project. It's easy to see that this is because [is_tag](https://github.com/VladimirMarkelov/ttdl/blob/423d865c9bfe70ebf3732d764d8ba692809bf2d0/src/fmt.rs#L711) is triggered before [is_project](https://github.com/VladimirMarkelov/ttdl/blob/423d865c9bfe70ebf3732d764d8ba692809bf2d0/src/fmt.rs#L717) is reached. Is there another use case where interpretation as a tag should have preference over interpretation as a project or is this just a random order? If the latter, I'd suggest to adjust that order.

**Comment by VladimirMarkelov** [comment]
Thank you! I am happy that people like my tool.

I'll fix it as soon as possible. Though, I am not going to make a new release until I finish with improving calendar. Anyway, after I fix the issue, you can pull the changes and build without waiting for the new release

**Comment by VladimirMarkelov** [comment]
Changed the order of highlighting. Tags had the highest priority before the fix. Now they are the last ones. You can pull the latest `master` branch and build.
