### ISSUE TITLE
[Feature Request] Please add support for multi line tasks.

### ISSUE THREAD

**Issue by debajyoti1990** [VladimirMarkelov/ttdl#76]

**Comment by VladimirMarkelov** [comment]
Could you elaborate the feature description? At this moment it can be understand in a few ways:

- Print subject in a few lines (it is already implemented: TTDL automatically if the command-line option `--wrap` is set)
- Support something like `new line` symbol inside a task subject, and print it correctly (the main question is "how to detect where to break lines?". In this case, do not forget that there is the command-line option `--short` that always print a task per line. I think, a multi-line task with option `--short` should print only its first line
- Support something like: a task occupies a few consecutive lines in the file `todo.txt`. This case seems incompatible with `todo.txt` format, so I doubt it would be implemented

**Comment by debajyoti1990** [comment]
To be honest I had used taskwarrior in WSL for some time so I thought it would be a nice addition in ttdl also, taskwarrior supports this by the way. But taskwarrior is a very complicated project and one can actually edit all tasks in any command line editor(I was using nano but others should also be good). Agree that multi line task is against the 1st principle of todo.txt but nevertheless it would have been a good option to have if todo.txt maintainers had shown interest.

Ttdl does not have to become taskwarrior, it's excellent as it is now. Thanks for your hard work🙏

**Comment by VladimirMarkelov** [comment]
I close the issue for now. If we really need this feature, we will reopen it
