### ISSUE TITLE
Documentation incorrect on Mac os x config location

### ISSUE THREAD

**Issue by SevereOverfl0w** [VladimirMarkelov/ttdl#81]
`/Users/{username}/Library/Preferences/ttdl/ttdl.toml` was not where ttdl was checking when I ran it through `dtruss`, instead it was looking at `/Users/{username}/Library/Application Support/ttdl/ttdl.toml`

**Comment by VladimirMarkelov** [comment]
Updated in master: https://github.com/VladimirMarkelov/ttdl/commit/127509bc6460f0270715e2658a86684eeab94a55
