### ISSUE TITLE
Support for scoop on Windows

### ISSUE THREAD

**Issue by aniketgm** [VladimirMarkelov/ttdl#82]
I was looking for a taskwarrior alternative for Windows and I'm glad I found this. It would be really helpful (if possible), if we could have support for scoop. I've been using scoop, since there was no package manager, untill recently (winget) and since It's Windows, you know what I mean. 😉

Thanks for making such a good tool.

P.S: I have to use Windows because of work. sad story.

**Comment by VladimirMarkelov** [comment]
I also use Windows, but in my case it seems easier :) Anyway, Scoop is a great project and it makes sense to add TTDL to its repo. As far as I see, TTDL can be added to "extra" bucket only as it is not popular enough. But I do not think it is a big deal. I need to do some research to figure out how to add a project to Scoop.

**Comment by aniketgm** [comment]
Just wanted to ask, no pressure though, do we have any progress here ?

I went through the scoop docs. It looks like one needs to add just a manifest file which will be used by scoop to install and update the package. I would love to contribute, but I think the first addition to scoop be done first by the owner of the tool. I can later add subsequent updates if required.

**Comment by aliesbelik** [comment]
1. If you need a prepared manifest here is one:
https://github.com/aliesbelik/poldi/blob/main/bucket/ttdl.json

2. I prefer to use it from my personal bucket but if you want to add `ttdl` to scoop's `Extras` please raise then at least [package request](https://github.com/ScoopInstaller/Extras/issues/new?assignees=&labels=package-request&projects=&template=package-request.yml&title=%5BRequest%5D%3A+) (but PR is welcome too).

3. Would be nice to add an archive with windows binaries for the latest release (currently available only for v4.2.0).

**Comment by VladimirMarkelov** [comment]
@aliesbelik I've opened both Request (https://github.com/ScoopInstaller/Extras/issues/13013) and PR(https://github.com/ScoopInstaller/Extras/pull/13014)

**Comment by aliesbelik** [comment]
Added to Extras bucket:

```
scoop bucket add extras
scoop install ttdl
```
