### ISSUE TITLE
I belive strict recurrence should be refferenced in the README

### ISSUE THREAD

**Issue by cyruseuros** [VladimirMarkelov/ttdl#88]
https://github.com/VladimirMarkelov/ttdl/blob/f7f23547bfd30bf7e302e44ec1d680531429f934/changelog#L261

Was a make-or-break feature for me (well, actually, being non-strict was)

**Comment by VladimirMarkelov** [comment]
Thank you for reporting this. I was sure I described it in the README. I'll update the doc

**Comment by VladimirMarkelov** [comment]
README is fixed.
